### ISSUE TITLE
Camera Issue

### ISSUE THREAD

**Issue by rooparsh** [lineageos-infra/updater#20]
I have le eco2 and i have downloaded the build for the same , codenamed s2. I am unable to access the camera in some apps namely , WhatsApp, Facebook , Instagram. And in some other apps, i have to switch between front and back camera multiple times before I can use camera. 
Error : Unable to start camera, please restart device.

**Comment by zifnab06** [comment]
This isn't for android issues. This is *only* for issues related to our infrastructure. Please take this to jira (jira.lineageos.org)
