### ISSUE TITLE
api calls for unoffical builds don't work on standalone

### ISSUE THREAD

**Issue by Charles-IV** [lineageos-infra/updater#22]
I'm using the docker-compose script, and while everything works fine (on my pc at least, rpi has weird issues), when I visit `/api/v1/grouper/unofficial/foo`, I get an internal server error, compared to an empty "response" when I visit `/api/v1/grouper/nightly/foo`.
Have a look here id you want to check: http://charles-iv.serveo.net (it's probably going to disconnect again, but I'll try to keep it online)
idk if this is the right place to report it or if you'll care because it's about unofficial stuff.

**Comment by jrior001** [comment]
Create a devices_local.json in the same format as https://github.com/LineageOS/hudson/blob/master/updater/devices.json for any unofficial devices.

**Comment by Charles-IV** [comment]
thanks, trying again now. I couldn't find any template for devices_local, and readme said it was optional, so I didn't know how to create it and didn't worry too much.
edit: nope, same results by the looks of things, except the device in the dropdown is duplicated, and my serveo link is no longer working.

**Comment by Charles-IV** [comment]
@harryyoud helped me out on irc, and it turned out to be a few problems with my environment. It's all fixed now.
