### ISSUE TITLE
Allow vote for a device

### ISSUE THREAD

**Issue by Mannshoch** [lineageos-infra/updater#26]
Please add possibility to vote for a Device. At moment I got more and more devices unsupported by lineageOS like my "Asus Transformer TF701" and "Samsung Galaxy Tab2 (espressowifi)" even I get actual Roms from other sources without problem I wish that lineage do support it. If possible I would vote for it.

**Comment by luk1337** [comment]
lmao.

**Comment by npjohnson** [comment]
That isn't how this works.

You either do the bringup on your own, or it doesn't happen.

We don't take device "requests" nor do we build for devices that we don't have.

**Comment by Demon000** [comment]
Find a dev suicidal enough to support those devices and buy him one.

**Comment by zifnab06** [comment]
@npjohnson covered it, but we don't support devices a maintainer doesn't own. Android's insanely complicated, every device has it's own unique challenges. Hopefully treble fixes this in the future. 

Additionally, this project is for issues with download.lineageos.org *only*, all device specific problems should be opened on JIRA.
