### ISSUE TITLE
j5xnlte USB-Ethernet perfomance degraded

### ISSUE THREAD

**Issue by Dimon160** [lineageos-infra/updater#42]
USB-Ethernet perfomance is degraded from 90+ to 50...70MBps.
Tested with:
17.1-20200624, 17.1-20201110
TP-LINK  EU-300 USB 3.0 to Gigabit Ethernet Network Adapter (RTL8153)
Magic iPerf, Speedtest by Ookla

This is not a new problem, it appeared in some builds 16.0

**Comment by luk1337** [comment]
This isn't a place to report such bugs, see https://wiki.lineageos.org/bugreport-howto.html.
