### ISSUE TITLE
No API parameters

### ISSUE THREAD

**Issue by augustin64** [lineageos-infra/updater#74]
Hi there,

The device manager can't find any update on my device.  
In fact, I've inspected the request with a mitm proxy, and it appears that it searches at [`https://download.lineageos.org/api/v1///2bc6f0b58c`](https://download.lineageos.org/api/v1///2bc6f0b58c), which of course returns a 404.

Device: `fajita`
Build number: `lineage_fajita-userdebug 12 SQ3A.220705.004 2bc6f0b58c`

Is this issue known and do I have to do the update manually ?

**Comment by luk1337** [comment]
Bet you're using some funny safety net hack that removes lineage related properties.

**Comment by luk1337** [comment]
FYI, the URL is prepared this way:

* https://download.lineageos.org/api/v1/{device}/{type}/{incr}
  * device = getprop ro.lineage.device
  * type = getprop ro.lineage.releasetype
  * incr = getprop ro.build.version.incremental

So if the first two are empty, then it's likely your silly magisk module :^)

**Comment by augustin64** [comment]
Ok, that's exactly the issue, thanks !
